---

language: ruby

sudo: false

dist: trusty

bundler_args: --without development

branches:
  only:
    - master

cache: bundler

before_install:
  - PATH=$(npm bin):$PATH # needed to install phantomjs via npm
  - if [ $(phantomjs --version) != '2.1.1' ]; then npm install phantomjs-prebuilt@2.1; fi
  - gem update --system # use the very latest Rubygems
  - gem install bundler # use the very latest Bundler

script:
  - bundle exec rake

env:
  global:
    - COVERAGE=true

matrix:
  fast_finish: true

  include:
    - rvm: jruby-9.1.12.0
      gemfile: gemfiles/rails_42.gemfile
      env: JRUBY_OPTS="-J-Xmx1024m --dev --debug"

    - rvm: jruby-9.1.12.0
      gemfile: gemfiles/rails_50.gemfile
      env: JRUBY_OPTS="-J-Xmx1024m --dev --debug"

    - rvm: jruby-9.1.12.0
      gemfile: gemfiles/rails_51.gemfile
      env: JRUBY_OPTS="-J-Xmx1024m --dev --debug"

    - rvm: 2.2.7
      gemfile: gemfiles/rails_42.gemfile

    - rvm: 2.2.7
      gemfile: gemfiles/rails_50.gemfile

    - rvm: 2.2.7
      gemfile: gemfiles/rails_51.gemfile

    - rvm: 2.3.4
      gemfile: gemfiles/rails_42.gemfile

    - rvm: 2.3.4
      gemfile: gemfiles/rails_50.gemfile

    - rvm: 2.3.4
      gemfile: gemfiles/rails_51.gemfile

    - rvm: 2.4.1
      gemfile: gemfiles/rails_42.gemfile

    - rvm: 2.4.1
      gemfile: gemfiles/rails_50.gemfile

    - rvm: 2.4.1
      gemfile: gemfiles/rails_51.gemfile

  allow_failures:
    - rvm: jruby-9.1.12.0
      gemfile: gemfiles/rails_50.gemfile
      env: JRUBY_OPTS="-J-Xmx1024m --dev --debug"

    - rvm: jruby-9.1.12.0
      gemfile: gemfiles/rails_51.gemfile
      env: JRUBY_OPTS="-J-Xmx1024m --dev --debug"
